version: "3.8"
services:
  myapp:
    image: my-node-app:latest
    container_name: my-node-app-container
    ports:
      - "3000:3000"
    networks:
      - mongo_net
      
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345678
      MONGO_INITDB_DATABASE: mydb
    networks:
      - mongo_net
    volumes:
      - my_mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8085:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345678
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: 12345678
    networks:
      - mongo_net

networks:
  mongo_net:
    external: true

volumes:
  my_mongo_data:  
    driver: local
